### ISSUE TITLE
hApp Download Failed 

### ISSUE THREAD

**Issue by birdfly** [holochain/launcher-tauri#89] opened 2022-10-18 09:59 UTC
**Describe the bug**
hApp download failed , I am trying to install the hApps listed in launcher ,but all throwed out  download failed message .

**To Reproduce**

**Expected behavior**

**Logs**
[2022-10-18T17:45:12.973028+08:00] INFO - Launch setup successful
[2022-10-18T17:45:30.916910+08:00] INFO - [LAIR] 
[2022-10-18T17:45:30.917283+08:00] INFO - [LAIR] # lair-keystore init generating secure config...
[2022-10-18T17:45:31.525861+08:00] INFO - [LAIR] 
[2022-10-18T17:45:31.525980+08:00] INFO - [LAIR] # lair-keystore init config:
[2022-10-18T17:45:31.526020+08:00] INFO - [LAIR] "/Users/xxxx/Library/Application Support/lair/0.2/lair-keystore-config.yaml"
[2022-10-18T17:45:31.526044+08:00] INFO - [LAIR] 
[2022-10-18T17:45:31.526097+08:00] INFO - [LAIR] # lair-keystore init connection_url:
[2022-10-18T17:45:32.207946+08:00] INFO - [LAIR] # lair-keystore connection_url # unix:///Users/xxxx/Library/Application%20Support/lair/0.2/socket?k=3QYAQmlfgw1uNGA524eC5GQKsyVUgygH9nuBgrospzk #
[2022-10-18T17:45:32.208019+08:00] INFO - [LAIR] # lair-keystore running #
[2022-10-18T17:45:32.326746+08:00] INFO - Launched lair-keystore
[2022-10-18T17:45:32.962277+08:00] INFO - [HOLOCHAIN 0.0.162] 
[2022-10-18T17:45:32.962311+08:00] INFO - [HOLOCHAIN 0.0.162] ###HOLOCHAIN_SETUP###
[2022-10-18T17:45:32.962323+08:00] INFO - [HOLOCHAIN 0.0.162] ###ADMIN_PORT:16674###
[2022-10-18T17:45:32.962332+08:00] INFO - [HOLOCHAIN 0.0.162] ###HOLOCHAIN_SETUP_END###
[2022-10-18T17:45:32.962628+08:00] INFO - [HOLOCHAIN 0.0.162] Conductor ready.
[2022-10-18T17:45:32.962659+08:00] INFO - Launched holochain
[2022-10-18T17:45:32.962684+08:00] INFO - LaunchHolochainProcessState::Success
[2022-10-18T17:45:33.064540+08:00] INFO - connect; url=Url2 { url: "ws://localhost:16674/" }
[2022-10-18T17:45:33.068080+08:00] INFO - request; msg=ListAppInterfaces
[2022-10-18T17:45:33.068345+08:00] INFO - run_to_socket;
[2022-10-18T17:45:33.068569+08:00] INFO - run_from_socket;
[2022-10-18T17:45:33.072498+08:00] INFO - request; msg=AttachAppInterface { port: Some(24259) }
[2022-10-18T17:45:33.074584+08:00] INFO - request; msg=ListApps { status_filter: None }
[2022-10-18T17:45:33.076314+08:00] INFO - request; msg=ListApps { status_filter: None }
[2022-10-18T17:45:33.726622+08:00] INFO - request; msg=GenerateAgentPubKey
[2022-10-18T17:45:35.238403+08:00] INFO - request; msg=InstallAppBundle(InstallAppBundlePayload { source: Path("/var/folders/br/x7zq95693ts109jgrnhjt5gw0000gn/T/app_to_installSystemTime { tv_sec: 1666086333, tv_nsec: 728235000 }.webhapp"), agent_key: AgentPubKey(uhCAkXuf-pHKDhriRMKZSfRg-Kl-xammBSuQXFpwtjl79_hnXkNai), installed_app_id: Some("DevHub-0.0.162"), membrane_proofs: {}, network_seed: None })
[2022-10-18T17:45:40.929842+08:00] INFO - [HOLOCHAIN 0.0.162] [2mOct 18 17:45:40.927[0m [33m WARN[0m holochain::conductor::api::api_cell: Using placeholder dpki
[2022-10-18T17:45:40.930110+08:00] INFO - [HOLOCHAIN 0.0.162] [2mOct 18 17:45:40.927[0m [33m WARN[0m holochain::conductor::api::api_cell: Using placeholder dpki
[2022-10-18T17:45:40.930137+08:00] INFO - [HOLOCHAIN 0.0.162] [2mOct 18 17:45:40.927[0m [33m WARN[0m holochain::conductor::api::api_cell: Using placeholder dpki
[2022-10-18T17:45:40.972408+08:00] INFO - request; msg=EnableApp { installed_app_id: "DevHub-0.0.162" }
[2022-10-18T17:45:40.993076+08:00] INFO - [HOLOCHAIN 0.0.162] [2mOct 18 17:45:40.992[0m [33m WARN[0m holochain::core::workflow::publish_dht_ops_workflow: failed_to_send_publish=RoutingDnaError(DnaHash(uhC0k1BllbZxAR97_6qTGomeb1Mep7pkOukcQJThd4oe0Ri1J6diJ))
[2022-10-18T17:45:40.993119+08:00] INFO - [HOLOCHAIN 0.0.162] [2mOct 18 17:45:40.992[0m [33m WARN[0m holochain::core::workflow::publish_dht_ops_workflow: failed_to_send_publish=RoutingDnaError(DnaHash(uhC0k5Ar60sEjDE406A3-6vK9gjLNl0e9Sai34lAlENMj8eY77TFp))
[2022-10-18T17:45:40.993137+08:00] INFO - [HOLOCHAIN 0.0.162] [2mOct 18 17:45:40.992[0m [33m WARN[0m holochain::core::workflow::publish_dht_ops_workflow: failed_to_send_publish=RoutingDnaError(DnaHash(uhC0ke22XklFbbluJ6KiZ-CkYIvS1Duv0wlRD5BnObHjvy9knmUde))
[2022-10-18T17:45:42.296852+08:00] INFO - request; msg=ListApps { status_filter: None }
[2022-10-18T17:45:42.303507+08:00] INFO - Launched Holochain 0.0.162
[2022-10-18T17:45:42.303861+08:00] INFO - request; msg=ListApps { status_filter: None }
[2022-10-18T17:45:42.306905+08:00] INFO - request; msg=ListApps { status_filter: None }
[2022-10-18T17:45:42.307884+08:00] INFO - request; msg=ListApps { status_filter: None }
[2022-10-18T17:45:47.716782+08:00] INFO - [HOLOCHAIN 0.0.162] [2mOct 18 17:45:47.715[0m [33m WARN[0m holochain::core::workflow::sys_validation_workflow: dna=uhC0ke22XklFbbluJ6KiZ-CkYIvS1Duv0wlRD5BnObHjvy9knmUde msg="DhtOp was rejected during system validation." op=StoreEntry(Signature(0x1b53e70c7dc3ee56d011127cff12ecf7ed2c4b6f9d8cd1ea872eb5a060cb8eb80f6a80851708ee03f6b27d41f6c30abf6433264ccefe6e2ba59628c5488ab606), Create(Create { author: AgentPubKey(uhCAkTi_kurZyJKD_OSvoL29gqrSEjnLWsflGQm9bJAkSwhYSgb01), timestamp: Timestamp(2022-10-09T08:13:10.350766Z), action_seq: 2, prev_action: ActionHash(uhCkkqEid7FBtRRoD5qwoHtTT6QQjacphMcUw-4T6g3x_4mgRlLR8), entry_type: AgentPubKey, entry_hash: EntryHash(uhCEkTi_kurZyJKD_OSvoL29gqrSEjnLWsflGQm9bJAkSwhYSgb01), weight: EntryRateWeight { bucket_id: 255, units: 0, rate_bytes: 0 } }), Agent(AgentPubKey(uhCAkTi_kurZyJKD_OSvoL29gqrSEjnLWsflGQm9bJAkSwhYSgb01)))
[2022-10-18T17:45:47.727500+08:00] INFO - [HOLOCHAIN 0.0.162] [2mOct 18 17:45:47.727[0m [33m WARN[0m holochain::core::workflow::sys_validation_workflow: dna=uhC0ke22XklFbbluJ6KiZ-CkYIvS1Duv0wlRD5BnObHjvy9knmUde msg="DhtOp was rejected during system validation." op=StoreRecord(Signature(0x1b53e70c7dc3ee56d011127cff12ecf7ed2c4b6f9d8cd1ea872eb5a060cb8eb80f6a80851708ee03f6b27d41f6c30abf6433264ccefe6e2ba59628c5488ab606), Create(Create { author: AgentPubKey(uhCAkTi_kurZyJKD_OSvoL29gqrSEjnLWsflGQm9bJAkSwhYSgb01), timestamp: Timestamp(2022-10-09T08:13:10.350766Z), action_seq: 2, prev_action: ActionHash(uhCkkqEid7FBtRRoD5qwoHtTT6QQjacphMcUw-4T6g3x_4mgRlLR8), entry_type: AgentPubKey, entry_hash: EntryHash(uhCEkTi_kurZyJKD_OSvoL29gqrSEjnLWsflGQm9bJAkSwhYSgb01), weight: EntryRateWeight { bucket_id: 255, units: 0, rate_bytes: 0 } }), Some(Agent(AgentPubKey(uhCAkTi_kurZyJKD_OSvoL29gqrSEjnLWsflGQm9bJAkSwhYSgb01))))
[2022-10-18T17:45:47.965780+08:00] INFO - [HOLOCHAIN 0.0.162] [2mOct 18 17:45:47.964[0m [33m WARN[0m holochain::core::workflow::app_validation_workflow: App validation is saturated. Util 16.00%. OPS/s avg 8428.86, this round 8429.18
[2022-10-18T17:45:47.966698+08:00] INFO - [HOLOCHAIN 0.0.162] [2mOct 18 17:45:47.966[0m [33m WARN[0m holochain::core::workflow::app_validation_workflow: App validation is saturated. Util 2.00%. OPS/s avg 8381.13, this round 3480.86
[2022-10-18T17:45:50.869161+08:00] INFO - [HOLOCHAIN 0.0.162] [2mOct 18 17:45:50.868[0m [33m WARN[0m kitsune_p2p_types::tx2::tx2_api: (api) req dropped dbg_name=Wire::Call local_cert=Cert(TuklLp..es1Fpo) peer_cert=Cert(6wAY4B..mGRvAw) elapsed_s=3.005976955
[2022-10-18T17:45:50.874026+08:00] INFO - [HOLOCHAIN 0.0.162] [2mOct 18 17:45:50.873[0m [33m WARN[0m kitsune_p2p_types::tx2::tx2_api: (api) req dropped dbg_name=Wire::Call local_cert=Cert(TuklLp..es1Fpo) peer_cert=Cert(vyJbYm..FrI8ZI) elapsed_s=3.011422554
[2022-10-18T17:45:50.878688+08:00] INFO - [HOLOCHAIN 0.0.162] [2mOct 18 17:45:50.878[0m [33m WARN[0m holochain::core::workflow::app_validation_workflow: App validation is saturated. Util 0.00%. OPS/s avg 560.79, this round 0.34
[2022-10-18T17:45:53.252637+08:00] INFO - [HOLOCHAIN 0.0.162] [2mOct 18 17:45:53.252[0m [33m WARN[0m holochain::core::workflow::sys_validation_workflow: dna=uhC0ke22XklFbbluJ6KiZ-CkYIvS1Duv0wlRD5BnObHjvy9knmUde msg="DhtOp was rejected during system validation." op=RegisterAgentActivity(Signature(0x1b53e70c7dc3ee56d011127cff12ecf7ed2c4b6f9d8cd1ea872eb5a060cb8eb80f6a80851708ee03f6b27d41f6c30abf6433264ccefe6e2ba59628c5488ab606), Create(Create { author: AgentPubKey(uhCAkTi_kurZyJKD_OSvoL29gqrSEjnLWsflGQm9bJAkSwhYSgb01), timestamp: Timestamp(2022-10-09T08:13:10.350766Z), action_seq: 2, prev_action: ActionHash(uhCkkqEid7FBtRRoD5qwoHtTT6QQjacphMcUw-4T6g3x_4mgRlLR8), entry_type: AgentPubKey, entry_hash: EntryHash(uhCEkTi_kurZyJKD_OSvoL29gqrSEjnLWsflGQm9bJAkSwhYSgb01), weight: EntryRateWeight { bucket_id: 255, units: 0, rate_bytes: 0 } }))
[2022-10-18T17:46:07.576446+08:00] INFO - [HOLOCHAIN 0.0.162] [2mOct 18 17:46:07.576[0m [33m WARN[0m kitsune_p2p_types::tx2::tx2_api: (api) req UNMATCHED RESPONSE resp_dbg_name=Wire::CallResp resp_byte_count=1586

**Additional context**

**Comment by matthme** [comment] 2022-10-18 10:03
Hi @birdfly and thank you for the bug report! There is already a duplicate issue of this (#64) and the problem is being worked on, so I will close this one to keep everything in one place.

**Closed as completed by matthme** 2022-10-18 10:03 UTC
Labels: bug

**Comment by matthme** [comment] 2022-10-18 10:05
As I wrote in the other issue, if you let the launcher running for a while to synchronize the files with other peers, it should hopefully work but feel free to make further comments on #64 .
