### ISSUE TITLE
Blank Window on Mac OS High Sierra 10.13.6

### ISSUE THREAD

**Issue by RogerValentine** [holochain/launcher-tauri#34] opened 2021-11-17 11:19 UTC
After launching the launcher App, nothing appears on this blank window; 

Attached logs and screen shots

[launcher.log](https://github.com/holochain/launcher/files/7554184/launcher.log)
![Screen Shot 2021-11-17 at 12 17 18](https://user-images.githubusercontent.com/6014099/142190950-c6deb91d-6519-4947-a395-3e3f4a655272.png)
![Screen Shot 2021-11-17 at 12 16 22](https://user-images.githubusercontent.com/6014099/142190954-9a7e95a1-1b85-425f-b1a6-b4ac5a0064e8.png)

**Comment by guillemcordoba** [comment] 2021-11-17 13:32
Hi! From the logs, this seems to be an old version of the launcher. Can you try with the new version [0.3.6](https://github.com/holochain/launcher/releases/tag/v0.3.6)?

**Comment by RogerValentine** [comment] 2021-11-17 15:04
re-installed, same problem, further more, I don't have acces to content in the menu (logs etc..)

**Comment by guillemcordoba** [comment] 2021-12-10 11:05
@RogerValentine thanks for the issue, I was able to reproduce and fix it. Can you confirmed this is fixed with [v0.3.7?](https://github.com/holochain/launcher/releases/tag/v0.3.7)

**Comment by RogerValentine** [comment] 2021-12-10 11:09
It works ! Thanx ! happy to help this great project ! any test you want me
to do, I'll be happy to comply !

Le ven. 10 déc. 2021 à 12:05, Guillem Córdoba ***@***.***> a
écrit :

**Comment by guillemcordoba** [comment] 2021-12-10 11:11
Awesome :) It's lovely to find people like you that want to help out!

**Closed as completed by guillemcordoba** 2021-12-10 11:11 UTC

**Comment by RogerValentine** [comment] 2021-12-10 13:01
Another question. I have been launching an app successfully (hippy kay hey)
Kitsuna, (some things to report there also if you got the good report link
or telegram to chat about it) - But there is no way to quit the launcher,
restart it, without restart your computer. Is a "quit button " planned for
the launcher ? cause I've been unable to follow the process indicated here

Le ven. 10 déc. 2021 à 12:11, Guillem Córdoba ***@***.***> a
écrit :

**Comment by guillemcordoba** [comment] 2021-12-10 13:14
Do you see the launcher icon in the systray of your mac? There is a "Quit" button there.

**Comment by RogerValentine** [comment] 2021-12-10 13:19
i see it now, I am french, so I coudn't figure out what systray ment ^^.
Its all fine.

Le ven. 10 déc. 2021 à 14:14, Guillem Córdoba ***@***.***> a
écrit :
