### ISSUE TITLE
Elemental chat and Elemental chess won't install (both hang on "Install").

### ISSUE THREAD

**Issue by anegg0** [holochain/launcher-tauri#36] opened 2021-11-29 02:06 UTC
**Describe the bug**

Elemental chat and Elemental chess won't install (both hang on "Install").
Kizuna will run, though.

**To Reproduce**

1. Launch launcher
2. Click "install new app" and select Add Elemental or Elemental chess package
3. Infinite hang.

**Expected behavior**
The happ to install and launch.

**Logs**

Github won't let me upload the log, [please find it here](https://drive.google.com/file/d/14Qq-t3tua2iSjPqxf2r4ktabmhe8Mdmz/view?usp=sharing)

**Screenshots**
![Screenshot from 2021-11-28 17-55-18](https://user-images.githubusercontent.com/8999121/143797249-4b94f22b-91f9-4e3f-8da1-69f56bd3bfaf.png)

**Desktop (please complete the following information):**
 - OS: [Ubuntu (Pop!_OS 21.04)]
 - Holochain Launcher Version [0.3.6]

**Comment by abe-njama** [comment] 2022-01-10 07:30
Thanks for raising this issue. We are looking into it.

**Comment by guillempuche** [comment] 2022-01-24 18:27
# Problem
Launcher never installs the app Elemental Chat on Mac M1 (latest  OS version). It's stuck on the loading screen.
<img width="1002" alt="imatge" src="https://user-images.githubusercontent.com/3519924/150842005-a84ff8ea-6cce-45fc-aaa0-729c78306048.png">

When this happens, I try to close the app (clicking the X icon) and then right click to "Quit app" on the icon Mac bar, but it doesn't work. Another way to quit the app would be pressing Command + Q, but it doesn't work.
<img width="514" alt="imatge" src="https://user-images.githubusercontent.com/3519924/150842952-180277a3-4dc7-415f-9778-f80846615066.png">

To quit the Launcher, I have to go to Activity Monitor (it's the Task Manager in Windows) and close this Launcher. 

I need to try other happs. If it goes well, I inform you.

---
# Enviroment

Versions:
- Holochain Launcher v0.3.7
- Holochain v0.0.119
- Lair Keystore v0.0.9
- Elemental Chat v0.0.1-alpha40


Logs:
```
[2022-01-24T19:21:28.448505+01:00] INFO - Installing: web_app_bundle = /Users/guillem/programacio/codi/holochain/demo_apps/elemental-chat.webhapp
[2022-01-24T19:21:51.978916+01:00] INFO - [HOLOCHAIN] [2mJan 24 19:21:51.978[0m [33m WARN[0m kitsune_p2p_types::tx2::tx2_pool_promote: channel logic end local_cert=Cert(qeMe4c..UfIbGA) peer_cert=Cert(SYVd4C..79DOs8)
[2022-01-24T19:22:22.521146+01:00] INFO - [HOLOCHAIN] [2mJan 24 19:22:22.520[0m [33m WARN[0m kitsune_p2p_types::tx2::tx2_pool_promote: channel logic end local_cert=Cert(qeMe4c..UfIbGA) peer_cert=Cert(SYVd4C..79DOs8)
[2022-01-24T19:22:53.057010+01:00] INFO - [HOLOCHAIN] [2mJan 24 19:22:53.056[0m [33m WARN[0m kitsune_p2p_types::tx2::tx2_pool_promote: channel logic end local_cert=Cert(qeMe4c..UfIbGA) peer_cert=Cert(SYVd4C..79DOs8)
```

**Comment by anegg0** [comment] 2022-01-25 02:11
Update: everything is running smooth with v0.3.7. on the same environment when I load elemental chess.

**Comment by guillemcordoba** [comment] 2022-01-28 15:04
Hi @anegg0 and @guillempuche could you try again with [launcher version 0.3.8](https://github.com/holochain/launcher/releases/tag/v0.3.8)? There was an issue that was fixed in that version of Holochain that I suspect was the cause for this behavior.

Unfortunately you'll have to wait until there are new application upgrades that target that holochain version as well.

**Comment by anegg0** [comment] 2022-01-28 19:18
Installed, @guillemcordoba. Running smooth. Will standby for new application upgrades :)

**Comment by guillempuche** [comment] 2022-01-29 17:38
Hi @guillemcordoba, I've installed the new launcher, but I see I have to wait for the chat.

On the new Launcher, the `About` info shows the previous Holochain version `0.0.123`, instead of `0.0.124`.

**Comment by matthme** [comment] 2022-11-21 08:23
I'm closing this because it refers to an outdated Launcher version.

**Closed as completed by matthme** 2022-11-21 08:23 UTC
Labels: bug
